version: "3"
services:
  postgres:
    container_name: "mypg-db"
    image: "postgres:9.6.1"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  redis:
    image: "bitnami/redis:latest"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
